### ISSUE TITLE
How to use inspectElement?

### ISSUE THREAD

**Issue by oldfeel** [asticode/go-astilectron#110]
````
  setupDevelopmentEnvironment() {
    this.mainWindow.openDevTools();
    this.mainWindow.webContents.on('context-menu', (e, props) => {
      const { x, y } = props;

      Menu
        .buildFromTemplate([{
          label: 'Inspect element',
          click: () => {
            this.mainWindow.inspectElement(x, y);
          }
        }])
        .popup(this.mainWindow);
    });
  }
````

**Comment by asticode** [comment]
@oldfeel seems like you're doing javascript directly, are you sure you need the GO overhead provided by this project? If so, you need to use this [function](https://github.com/asticode/go-astilectron/blob/master/window.go#L357) in order to show dev tools. 

But once again, if your use of GO is minor, I'd strongly recommend using Electron directly.

Does that fix your problem ?

**Comment by oldfeel** [comment]
@asticode Thanks, I want to write a video conferencing client. I need to transfer data between go and js frequently. I feel that this project is more convenient than using electrons directly. However, the inspectElement method is needed to debug the interface. I hope that go-astilectron can provide it. This method does not matter, go-astilectron is good enough.

**Comment by oldfeel** [comment]
@asticode Yes, Thank you very much.
