### ISSUE TITLE
Is this support IOS or android?

### ISSUE THREAD

**Issue by nickhell** [asticode/go-astilectron#112]

**Comment by asticode** [comment]
@nickhell unfortunately this will be supported when electron will be supported on iOS and Android which is not the case right now.

**Comment by Noofbiz** [comment]
What I've done in the past is use the same html/css/js as the astilectron app in an Android WebView https://developer.android.com/reference/android/webkit/WebView and then written the glue and native logic bits in Java. I'm not sure if it's possible to do that in iOS since I don't have a Mac for xCode, but it should be similar. It ends up looking the same, but you do have the issue with a bifurcated code base; it would be nice (and it should be possible with gomobile bind!) to write it all in Go, but I didn't have time for that myself 😝
