### ISSUE TITLE
Compatibility with Electron infrastructure

### ISSUE THREAD

**Issue by MichaelLeachim** [asticode/go-astilectron#116]
Hello, thank you for wonderful library. 
I would like to know what is the best way to use it in conjunction
with Electron infrastructure. 

For example, I would like to use 
https://github.com/electron-userland/electron-forge
to generate optimal packages for multiple platforms. 
But I don't exactly understand how, given that go-astilectron
uses, afaik, its own packaging/distribution process

Thanks

**Comment by asticode** [comment]
@MichaelLeachim `go-astilectron` is not compatible with most Electron tools since its core is in GO and not in NodeJS (the final binary is a GO binary communicating with NodeJS, not the other way around). That's why I had to create its own packaging/distribution process.

Therefore unfortunately I don't think there's any way for you to use electron-forge. Sorry about that.

Does that answer your question?

**Comment by MichaelLeachim** [comment]
@asticode   
Okay, then I will have to go "Electron spawning binary with embedded server" route.
Yes, thank you.

**Comment by asticode** [comment]
Cheers
