### ISSUE TITLE
How to add a keyboard shortcut?

### ISSUE THREAD

**Issue by rcholic** [asticode/go-astilectron#119]
I found all of the shortcuts that regular MacOS apps allow do **NOT** work with the built go-astilectron app. For example, `cmd + w` to close the app window. 

I wonder how to register key shortcuts in go-astilectron. thanks

**Comment by asticode** [comment]
No shortcuts are registered by default.

The simplest way to register one, is to add an item to your menu with either an accelerator or a role.

If you add a role to your item such as [Close](https://github.com/asticode/go-astilectron/blob/master/menu_item.go#L25), the default shortcut will also be available. Otherwise you can set the [Accelerator option](https://github.com/asticode/go-astilectron/blob/master/menu_item.go#L82) of your menu item.

Does that answer your questions?

**Comment by asticode** [comment]
@rcholic did it fix your issue?

**Comment by asticode** [comment]
Closing the issue for now

**Comment by adracea** [comment]
Hey @asticode I'm currently trying to do the same thing and I'm experiencing some conflicting behavior with the default role buttons . IE: 
```golang
SubMenu: []*astilectron.MenuItemOptions{
				{Role: astilectron.MenuItemRoleClose},
}
```
Will not do anything on pressing CTRL+W(as advertised on the button itself .
On the other hand , doing will create the same close button with working close functionality + shortcut : 
```golang
SubMenu: []*astilectron.MenuItemOptions{
{Accelerator: astilectron.NewAccelerator("Control","W"),Label: astilectron.PtrStr("Close"),OnClick: func(e astilectron.Event)(deleteListener bool){
					w.Close()
					return
				},},
}
```
Also doing something like the following won't work : 
```golang
SubMenu: []*astilectron.MenuItemOptions{
				{Accelerator: astilectron.NewAccelerator("Control","X),Role: astilectron.MenuItemRoleQuit},
}
```

I tried figuring out if it's coming from astilectron or electron but I haven't used either enough .
I *think* it might be related to https://github.com/electron/electron/issues/2812 but I'm not sure ?

**Comment by asticode** [comment]
@adracea do you have links that explain what you found after a bit more digging?
