### ISSUE TITLE
application is not opening

### ISSUE THREAD

**Issue by harshayk** [asticode/go-astilectron#122]
I created appliaction using astilectron
it created myapp.app in darwin-amd64 
but its not opening by clicking it
then iam running the executable inside the folder it is opening.
can u plz help me to overcome this problem

**Comment by bbuehrig** [comment]
Same here!

**Comment by harshayk** [comment]
ya same error ﻿﻿﻿﻿LSOpenURLsWithRole() failed with error -10810 for the file
@

**Comment by asticode** [comment]
@harshayk then you should check out [this issue](https://github.com/asticode/go-astilectron/issues/103)

Are your issues fixed?

**Comment by asticode** [comment]
Did it fix your issues?

**Comment by harshayk** [comment]
one thing i have to know that is where i have use these functionalities
in main.go

**Comment by harshayk** [comment]
??

**Comment by asticode** [comment]
@harshayk first you should check out [this comment](https://github.com/asticode/go-astilectron/issues/103#issuecomment-383433011) that may explain the root cause of your problem (relative paths).

To avoid using relative paths in your app, you can use `os.Executable()` or `a.Path().DataDirectory()` to transform your relative paths into absolute paths.

**Comment by harshayk** [comment]
thanks its working
