### ISSUE TITLE
failed: astihttp: downloading in writer

### ISSUE THREAD

**Issue by qjin2113** [asticode/go-astilectron#128]
FATA[0351] bundling failed: bundling for environment darwin/amd64 failed: binding data failed: provisioning the vendor failed: provisioning electron vendor for OS darwin and arch amd64 failed: downloading https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip into /var/folders/zs/bn8sbvbj67gg5_4yzr6cn19r0000gn/T/astibundler/cache/electron-darwin-amd64-1.8.1.zip failed: astihttp.Download failed: astihttp: downloading in writer failed: astihttp: copying content from https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip to writer failed: unexpected EOF

**Comment by asticode** [comment]
@qjin2113 this means that the bundler couldn't download https://github.com/electron/electron/releases/download/v1.8.1/electron-v1.8.1-darwin-x64.zip. Are you sure the machine you're downloading this file with has an internet connection? What happens if you try again (that may be a temporary network issue)?
