### ISSUE TITLE
build problem in Windows 10: 

### ISSUE THREAD

**Issue by rcholic** [asticode/go-astilectron#130]
I got the following errors reported when doing a `go build` in Windows 10 with the example app (for listing files and directories):

```
.\main.go:43:11: unknown field 'Homepage' in struct literal of type bootstrap.Options
.\main.go:148:9: cannot use func literal (type func(*astilectron.Astilectron, *astilectron.Window, *astilectron.Menu, *astilectron.Tray, *astilectron.Menu) error) as type bootstrap.OnWait in field value
.\main.go:160:17: unknown field 'MessageHandler' in struct literal of type bootstrap.Options
.\main.go:162:16: unknown field 'WindowOptions' in struct literal of type bootstrap.Options
```
bootstrap.Options {
...
Line 43: `Homepage: "index.html",`
Line 148: `OnWait: func(_ *astilectron.Astilectron, iw *astilectron.Window, _ *astilectron.Menu, _ *astilectron.Tray, _ *astilectron.Menu) error {`
...
}

Is there anything obvious I'm missing for build on Windows?

**Comment by asticode** [comment]
@rcholic the bootstrap has evolved so that it can handle several windows. Therefore its options have evolved as weel.

Basically there's a `Windows` attribute at the root of the options which is a `[]*Window`. You can specify an `Homepage`, `MessageHandler` and `Options` to each `Window` individually.

Does that make sense?

**Comment by rcholic** [comment]
I see. thanks!

**Comment by asticode** [comment]
Yes it does, it's not OS-specific :)

Cheers
