### ISSUE TITLE
Don't unzipped astilectron-v0.25.0.zip

### ISSUE THREAD

**Issue by lansi951** [asticode/go-astilectron#132]
Windows 10 x64

Set `DataDirectoryPath: "D:\\go\\src\\demo\\resources"`.

`go build`

`.\demo.exe -d -v`

Error "Unable to fine Electron app at D:\go\src\demo\resources\vendor\astilectron\main.js"

D:\go\src\demo\resources\vendor
.\astilectron
.\electron-windows-amd64
.\astilectron-v0.25.0.zip
.\electron-windows-amd64-v1.8.1.zip
.\status.json

Unzipped files in .\electron-windows-amd64 directory.

.\astilectron directory is empty.

**Comment by asticode** [comment]
Here's what happened:

- the previous astilectron version was 0.24.0
- therefore the zip file that was downloaded was the 0.24.0 version
- the astilectron version was bumped to 0.25.0 this weekend
- as you're building your project manually, it didn't fetch the 0.25.0 zip file

And therefore the process failed.

Hence if you want to build your project manually, when there's a change of version in astilectron:

- either you bundle your app using the bundler so that it downloads all the proper files
- either you download all the proper files manually

Cheers

**Comment by lansi951** [comment]
Update and reinstall bundler
```
go get -u github.com/asticode/go-astilectron-bundler
go install github.com/asticode/go-astilectron-bundler/astilectron-bundler
astilectron-bundler -v
```

**Comment by asticode** [comment]
Cheers
