### ISSUE TITLE
Escape hatch to use power monitor events (suspend, resume, ...)

### ISSUE THREAD

**Issue by pjebs** [asticode/go-astilectron#161]
The read me says that power monitor events have not been implemented.
Is there an "escape hatch" to go direct to node and use features that aren't implemented.
Perhaps using gopher.js to convert go code to js?

**Comment by asticode** [comment]
@pjebs in your `.js` file, you have access to NodeJS. For your searches, bare in mind that your `.js` is equivalent to the `renderer`.

Therefore what I would try is instanciate `electron` in your `.js` file, try and see if you manage to do what you're looking to do. Otherwise, I would try to instanciate the `remote` attribute of `electron` and try to achieve what you're looking to achieve.

Does that make sense?

**Comment by pjebs** [comment]
Lol none of it actually made sense. Perhaps if I play around with your project first, it will then start to make sense.

I am the creator if this golang-reactjs bindings package: https://medium.com/@rocketlaunchr.cloud/go-with-react-de5ee4f01df9

I was just looking for ways to integrate it with your package.
