### ISSUE TITLE
Can't figure out ResourcesPath / Homepage for vue

### ISSUE THREAD

**Issue by sgehrman** [asticode/go-astilectron#162]
I've been trying to get Homepage and ResourcesPath to work.

		ResourcesPath: "resources/app/vue/dist"
		Homepage:       "index.html"

or 
		ResourcesPath: "resources/app/vue/dist"
		Homepage:       "vue/dist/index.html"

But I always get an error.  Either the index.html won't load, or it can't find the resources.  Or I get an error saying chrome won't load local files.

I did noticed that "app" is appended to the resourcesPath, not sure if I have to work around that or fork bootstrap.

Let me know if I'm doing it wrong.
```
├── app
│─── vue
│       ├── dist
│       │   ├── css
│       │   │   └── app.e2713bb0.css
│       │   ├── favicon.ico
│       │   ├── img
│       │   │   └── logo.82b9c7a5.png
│       │   ├── index.html
│       │   └── js
│       │       ├── app.cddc4d4e.js
│       │       ├── app.cddc4d4e.js.map
│       │       ├── chunk-vendors.62c5a450.js
│       │       └── chunk-vendors.62c5a450.js.map
```

**Comment by asticode** [comment]
The `ResourcesPath` allows you to indicate another path to store your `resources` in your project. For instance, if you'd like to store your resources in your GO project in `path/to/resources`, you should use this option. Bare in mind that it's relative to the path of your GO project and that the default value is `resources`. That's why in the demo the resources are in a folder names `resources`. When the resources will be unbinded, they will be stored in the exact same path relative to the app data folder.

The `Homepage` allows you to indicate the file to open on startup relative to the mandatory bootstrap `app` folder.

I'm not a Vue nor JS guru, but what I would do is:

```
main.go
|- resources
    |- app
        |- index.html
|- vue
```

I would develop in the folder `vue` which is never binded to the binary. And before bundling, I would generate the proper dist files directly in the `app` folder.

That way you can keep your dev and dist files separated, and only the dist files are binded to the binary. In this case you would need to set the attributes that way:

```
ResourcesPath: "resources"
Homepage:       "index.html"
```

Or not event set `ResourcesPath` since it defaults to `resources`.

Does that fix your issue?

**Comment by sgehrman** [comment]
I'll try some more.  I have this vue folder, and I build the dist folder from that code.  Ideally I could just point the home page to vue/dist/index.html, but then that index.html can't find it's css and js files.  In the index.html is has links like /js/app.cddc4d4e.js  

How can I make it so the index.html can locate it's js files to import?  I know in Webpack you can set some paths for this.  I'm not an expert, so I don't know what's possible with your code.  I assumed the resourcesPath would do this.

Thanks.

**Comment by sgehrman** [comment]
I did get it working by moving my index.html and css/js to the resource/app, but within the code images aren't being found. <img alt="Vue logo" src="/img/logo.82b9c7a5.png">

they use the path /img but if I move the files to resources/app the path should be "img/xx.png" without the /

**Comment by sgehrman** [comment]
basically I just did this to create the test vue app

npm install -g @vue/cli
vue create my-project

And put that vue project inside resources/app and build it using:
npm run build
that creates the dist folder

**Comment by asticode** [comment]
Problem is that the `Homepage` attribute is used to tell Electron which file to open on startup. If you provide a path to a file on your file system it will consider the root (`/`) is the root of your file system. Therefore your images won't be found.

If you have no way of updating the prefix of your images (which would be weird), you'll need to spawn your own web server that will serve your static files and indicate its URL in the `Homepage` attribute.

**Comment by JRascagneres** [comment]
@sgehrman Hey. Can I ask if you figured it out? I'm in the exact same scenario where my css and js is now working but my images aren't.
