### ISSUE TITLE
Using React JS with a UI Kit

### ISSUE THREAD

**Issue by zanitee** [asticode/go-astilectron#219]
Is it possible to use React with this project? How would one go about using a UI kit like material-ui.com inside a go-astilectron project?

**Comment by asticode** [comment]
@zanitee I've never used React myself but I don't see why you couldn't.

Indeed, once you've created a window you tell it which .html page to open. This page can contain anything you want, including React stuff. If you take a look at the [demo](https://github.com/asticode/go-astilectron-demo/blob/master/resources/app/index.html), you can see I've included custom scripts. You can do the same with React.

Does that answer your question?

**Comment by benitogf** [comment]
Hello @asticode thanks for this project, so far it looks great! I have tried to use it with https://github.com/facebook/create-react-app but found some issues with the url paths, seems that create-react applications will prefix the paths with '/'

![image](https://user-images.githubusercontent.com/1633813/78209978-460ae380-74db-11ea-88fb-f70d0d1f1fca.png)

![image](https://user-images.githubusercontent.com/1633813/78210099-a3069980-74db-11ea-8531-3e9cc647bd08.png)

Guess that this could be fixed by manually changing the refs to relative, but I would prefer to solve it on the Go side, my goal would be to have astilectron behave like https://github.com/sindresorhus/electron-serve do you have any pointers on how to achieve this?

Thanks, have a nice day!

**Comment by asticode** [comment]
The only way I see to fix that in GO, is to spawn a GO server that would serve your `React` files instead of loading local assets using relative path. That way, you would have control on what is the root of the paths you're providing the `src` attributes. Does that make sense ?
