### ISSUE TITLE
To change go, HTML, js, CSS, you must execute astilectron-bundler

### ISSUE THREAD

**Issue by lengnuan-v** [asticode/go-astilectron#223]
Modify go, HTML, js, CSS, must execute astilectron-bundler, can be changed, the original modification of the static file refresh can be, now is not available, what method can be more convenient to view the modified effect

**Comment by asticode** [comment]
In development mode, and if you're using the `bootstrap` + `bundler` like in the [demo](https://github.com/asticode/go-astilectron-demo/) here's what you can do to speed up refreshes :

1) Get the `working directory`

```go
wd, err := os.Getwd()
// TODO process err
```

2) Remove `Asset`, `AssetDir` and `RestoreAssets` bootstrap attributes
3) In `AstilectronOptions` add `BaseDirectoryPath` attribute with value `wd`
4) Run your app using `go run *.go`

The first run will be a little bit long since it will download both `astilectron` and `electron`, but the runs after that should be quicker.

Here's a [gist](https://gist.github.com/asticode/6f9ebf8169ef773551321c158dfdb26f) to show you how the demo would look like with those changes.

Does that fix your problem ?

**Comment by lengnuan-v** [comment]
Problem solved, thanks ~
One more question
How do I make the compiled files generate installable DMG

**Comment by asticode** [comment]
> How do I make the compiled files generate installable DMG

For now this is not possible.

**Comment by lengnuan-v** [comment]
Astilectron - bundler
Unable to compile the executable, the generated file flashes open and disappears without error

**Comment by asticode** [comment]
Without logs there's nothing much I can do. Can you paste your app logs here?
