### ISSUE TITLE
Is this possible to embed vendor files?

### ISSUE THREAD

**Issue by egorsmkv** [asticode/go-astilectron#270]

**Comment by egorsmkv** [comment]
What do I mean? Is this possible to embed resources files and vendor files using, for example, by this tool - github.com/shurcooL/vfsgen ?

Where is this needed? I don't want to unzip all the files to an app's folder.

**Comment by asticode** [comment]
Are you using the boostrap and the bundler ?

**Comment by egorsmkv** [comment]
Yes, I do

**Comment by asticode** [comment]
Some files **need** to be unzipped in the app's folder : this is the case for `astilectron`'s vendor files and is part of the `bundler` process. This is also the case for your app's icons.

As for your custom files, you're free to do whatever you want with them :

- if you place them in the `resources` dir, they will be embedded during the `bundler` process
- but if you place them elsewhere, you can use your tool for instance. You just need to do so before using the bundler so that it picks up your generated `.go` files

**Comment by egorsmkv** [comment]
I understand. Thanks.
