### ISSUE TITLE
Bug : I cant run it

### ISSUE THREAD

**Issue by Philiphil** [asticode/go-astilectron#3]
Hi,
First I'd like to thank you a lot for this project, i was using go-thrust.

This happens when i'm trying to run example 1 (or any example actually)

> C:\Users\xxx\go\src\github.com\asticode\go-astilectron\examples\1.basic_window>go run main.go -v
> 2017/05/06 08:53:03 ←[37mDEBU←[0m Starting... ←[32mapp_name←[0m= ←[32mfile←[0m=std.go:122017/05/06 08:53:03 ←[37mDEBU←[0m Provisioning... ←[32mapp_name←[0m= ←[32mfile←[0m=std.go:12
> 2017/05/06 08:53:03 ←[34mFATA←[0m starting failed: provisioning failed: retrieving provisioning status failed: opening file 
> C:\Users\xxx\go\src\github.com\asticode\go-astilectron\examples\1.basic_window\"C:\Users\xxx\go\"\src\github.com\asticode\go-astilectron\examples\vendor\status.json 
> failed: open C:\Users\xxx\go\src\github.com\asticode\go-astilectron\examples\1.basic_window\"C:\Users\xxx\go\"\src\github.com\asticode\go-astilectron\examples\vendor\status.json:
> La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. ←[32mapp_name←[0m= ←[32mfile←[0m=std.go:20
> exit status 1

And when i'm trying to run some code looking like this : 

> func displayloading(){
>   for{
>       timer1 := time.NewTimer(time.Second * 5)
>       <-timer1.C
>       fmt.Println("loading ...")
>     }
> }
> func window_init() {
>    go displayloading()
>  go runwebserver()
> var a *astilectron.Astilectron
>    a, _ = astilectron.New(astilectron.Options{})
> 
>   defer a.Close()
>   a.HandleSignals()
>    a.Start()
>   ws, _ := a.NewWindow("http://127.0.0.1:"+port+"/"+folder+"/"+index, &astilectron.WindowOptions{
>     Center: astilectron.PtrBool(true),
>     Height: astilectron.PtrInt(600),
>     Width:  astilectron.PtrInt(800),
>   })
> 
>   ws.Create()
>   a.Wait()
> }

"Loading ..." appears 4 times and then nothing never happens

My user doesnt have administrator rights, I think that this may be the reason why.

Do you have any ideas of how to fix this ?
Here's my spec : 
go version go1.7.5 windows/amd64
Windows 7, 64bit.

Thanks again.

**Comment by asticode** [comment]
@Philiphil thanks for the nice words :)

First off I've updated the default logger because it looked really bad in windows. It should look better now.

1. Could you tell me what the command "go env" outputs ? Indeed the path `go-astilectron` builds is `C:\Users\xxx\go\src\github.com\asticode\go-astilectron\examples\1.basic_window"C:\Users\xxx\go"\src\github.com\asticode\go-astilectron\examples\vendor\status.json` and I'm trying to see why the path is built this way.
2. Is the URL given in the `NewWindow` fully loaded at some point ? Indeed the `Create` function will wait for the `did-finish-load` electron's event to avoid asynchronous errors so if it never finishes loading it will block forever.

Let me know.

**Comment by asticode** [comment]
Also for the second example could you set up the logger in debug mode so that I can see what `go-astilectron` is doing ?

Cheers

**Comment by Philiphil** [comment]
Hi, 
I found what was causing this
changing my "run.bat" from `set gopath="C:\Users\xxx\go\"` to `set gopath=C:\Users\xxx\go\` fixed everything.
