### ISSUE TITLE
Chrome DevTools extensions e.g. React / Vue DevTools

### ISSUE THREAD

**Issue by wickedst** [asticode/go-astilectron#316]
What's the best way to load a Chrome extension in the Electron window?

I've found the guide for using extensions in the [Electron docs](https://www.electronjs.org/docs/tutorial/devtools-extension)

How can I adapt this in go-astilectron... maybe via [Window.ExecuteJavaScript](https://pkg.go.dev/github.com/asticode/go-astilectron@v0.20.0?utm_source=gopls#Window.ExecuteJavaScript)?

**Comment by asticode** [comment]
Right now I don't think you can. Except if you can access the default session from the `remote` object in your JS (but this has been deprecated so I wouldn't recommend it).

If I understand the doc correctly, one would need to add a `func LoadExtension(path string) error` method in the [Session struct](https://github.com/asticode/go-astilectron/blob/master/session.go#L30) that would make sure to call [loadExtension](https://github.com/electron/electron/blob/v11.1.0/docs/api/session.md#sesloadextensionpath) in JS.

Then all you'd need to do is make sure to put your extension in your resources (so that it gets bundled with your binary), and call the `LoadExtension` function with the path to the extension in your resources.

If you feel like submitting a PR, go for it. I can provide more information.

Cheers

**Comment by wickedst** [comment]
I've had a go at it here: #317 

I'm sure there's more to it than this, hopefully you won't mind pointing me in the right direction! I'm the front-end part of the team so my Go skills are beginnner at best :)

**Comment by asticode** [comment]
No worries, I'll try to guide you the best I can.

Your PR is a good first step for the GO part, I'll make a review shortly. However you also need to make a PR for [astilectron](https://github.com/asticode/astilectron) for the JS part :

1) Add a `sessionCmdLoadExtension` and `sessionEventLoadedExtension` [here](https://github.com/asticode/astilectron/blob/master/src/consts.js#L56)
2) Clone this [switch case](https://github.com/asticode/astilectron/blob/master/index.js#L159) and adapt it to call `loadExtension` (bare in mind that in this case `elements[json.targetID]` is the session)
3) Make sure both constants and switch cases are ordered alphabetically

Good luck

**Comment by wickedst** [comment]
[Done ](#317) and [done](https://github.com/asticode/astilectron/pull/44) 

Once you're happy I can PR an update to the docs as well

**Comment by CarsonSlovoka** [comment]
It looks like the issue has been completed. Consider to closed?
