### ISSUE TITLE
running the menu example with bootstrap example

### ISSUE THREAD

**Issue by beardww** [asticode/go-astilectron#34]
I've tried unsuccessfully to invoke a menu using /example/8.bootstrap, and would like suggestions.

I've used the AdaptWindow, and AdaptAstilectron functions via /example/8.bootstrap, in the bootstrap.run options. In the case of AdaptAstilectron, it works, and then it's quickly replaced when the bootstrap loads  and in the case AdaptWindow, it ignores the creation of the menu altogether, with the exception of loading a popup menu onto the canvas.

**Comment by asticode** [comment]
@beardww there's nothing you could have done since the `AdaptAstilectron` function is executed before `a.Start()`. However I've just pushed a new option that I should have added from the get go: `OnWait`. Its signature is `func(a *astilectron.Astilectron, w *astilectron.Window) error` and it's executed juste before `a.Wait()`. Therefore you can create your menu using this callback.

Let me know how it goes and close this issue if this fixes your problem.

**Comment by beardww** [comment]
Thank you Astcode. Built binary in OSX 10.10.5/go1.8.3 darwin/amd64 and tested binary on OSX 10.10.5 and win7 SP1/AMD successfully.
