### ISSUE TITLE
How to build the app package for macOS ?

### ISSUE THREAD

**Issue by lunny** [asticode/go-astilectron#38]
Maybe another tool to do the pack thing for macOS?

**Comment by asticode** [comment]
Checkout this useful comment: https://github.com/asticode/go-astilectron/issues/13#issuecomment-323478035.

It provides a link to a repo doing just that I think.

Does that fulfill your demand?

**Comment by lunny** [comment]
@asticode I don't think that's the same thing. A macOS package just like directory `electron-darwin-amd64` 's structure. But put the binary and resources on it. For example, https://github.com/murlokswarm/macpack implemented a pack tool for macOS for https://github.com/murlokswarm/app project.

**Comment by asticode** [comment]
@lunny I've implemented a [bundler](https://github.com/asticode/go-astilectron-bundler) that will bundle your `astilectron` app if you've used the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) (which has its own repo now and has been updated. It's recommended to use it.).

The bundler will bundle for MacOS (creating the files structure your issue is about) but also for Windows (adding a nice .ico if you have one).

Check out the new [demo](https://github.com/asticode/go-astilectron-demo) repo to see a working example. I will remove the examples from `astilectron` shortly and add more features to the demo.

Does that fix your issue?

**Comment by lunny** [comment]
Great job! I will check that.

**Comment by lunny** [comment]
@asticode but some different things between my situation. I used github.com/lunny/gop to manage my repos which is not in $GOPATH. Could the bunlder be more flexible?

**Comment by asticode** [comment]
@lunny I can surely try to make it more flexible :)

Can you create an issue in the [bundler](https://github.com/asticode/go-astilectron-bundler)'s repo so that it's easier to track for the community? 

And in this issue can you paste the logs you get when executing the bundler (with the `-v` flag) and explain precisely where this difference is problematic?

I will close this issue as it's now moved to the [bundler](https://github.com/asticode/go-astilectron-bundler) repo.

Cheers
