### ISSUE TITLE
Standalone binary instructions?

### ISSUE THREAD

**Issue by spieglt** [asticode/go-astilectron#40]
I see that example 5 concerns single binary distributions, but I'm not sure what these commands do exactly:

````
$ go generate examples/5.single_binary_distribution/main.go
$ go run examples/5.single_binary_distribution/main.go examples/5.single_binary_distribution/vendor.go -v
````

Does this just apply to the last example you've run? Where does it put the binary? Also, the `go generate` command works on one of my machines, but on another machine I get:
```
bindata: Failed to stat input path '..\vendor': GetFileAttributesEx ..\vendor: The system cannot find the file specified.
examples\5.single_binary_distribution\main.go:12: running "go-bindata": exit status 1
```

It seems as though this machine doesn't create the go-astilectron\examples\vendor directory when running the examples for some reason. Both are Windows 10, Go 1.8.3. 

Separate question: running `go install` on any of the examples seems to output a standalone binary in my `go\bin` directory. Are these true standalone binaries? If so, what is the purpose of example 5? Also, if someone could give me a clearer idea of what the go-astilectron-bundler is for I'd be very grateful. Thanks!

**Comment by spieglt** [comment]
Ah, I see that the executables output to `go\bin` are _not_ self-sufficient and recreate the `go\src\github.com\asticode\go-astilectron\examples\vendor` directory if it's not there.

**Comment by spieglt** [comment]
So my question is: what is the proper way to create a go-astilectron binary that can be copied to and run on a machine that has never had Go or Electron installed, without creating or shipping any additional files. Or can this be done?

**Comment by spieglt** [comment]
Another update: the `go generate` failing (resulting in the `Failed to stat input path` issue) was resolved by properly setting my GOBIN and GOPATH environment variables.

**Comment by asticode** [comment]
@spieglt theorically here are the final files your user needs on his computer to launch an astilectron app :

- a valid go binary containing your code
- vendor files (electron, astilectron)
- external resource files (html, css, js, icons)

Furthermore, you'll need additional os-specific files to bundle your app so that the executable looks nice to your user (specific file structures to get a nice macos bundle structure for instance). Those files are not mandatory for astilectron to work, but make your executable look good for your user.

The idea is to embed only the files your binary needs in order to work properly directly in your binary: this is done with [go-bindata](https://github.com/jteeuwen/go-bindata) and works by storing your files content as GO `[]byte`.

Right now there are no guided way to do it but I intend to change it. That's why I've just created [go-astilectron-bundler](https://github.com/asticode/go-astilectron-bundler). The idea is simple:

- coupled with the [go-astilectron-bootstrap](https://github.com/asticode/go-astilectron-bootstrap), it will embed the vendor and the resource files before building your GO binary.
- it will then add the proper os-specific files to make your binary look good

That way for each os/arch you desire you'll get the proper files to present the users.

**Comment by asticode** [comment]
But back to your questions regarding the `5.single_binary_distribution` example:

- the `go generate` command will use `go-bindata` to embed the `vendor` folder in your binary. That way when you’ll execute the binary, it will first disembed the `vendor` folder and recreate it on disk. But for that to work you need to have the `vendor` folder already (which is a pain in the ass and which the [bundler](https://github.com/asticode/go-astilectron-bundler) will correct). That’s why you need to run one of the other examples before running the `go generate` command: this will set up the `vendor` folder and you’ll be able to embed it afterwards using the `go generate` command.
- when running `go run`, it builds your binary in a temp folder that golang automatically creates. This is used to quickly run your program. If you want to use the binary afterwards I urge you to use the `go build` command instead.

**Comment by asticode** [comment]
Does that answer your questions?

Feel free to ask some more, I'm pretty sure I haven't been really clear about this process in the documentation so others may the same questions. And that should help me enhance the documentation.

Cheers

**Comment by spieglt** [comment]
So I could theoretically just embed the vendor and resource files into my Go executable, and upon starting, just write them and launch the app? I'm already using go-bindata for a similar purpose in my project so it wouldn't be a big change. And there's no reason they have to be in your GOPATH specifically, correct? They could just be beside the main executable, wherever it happens to be?

Also, when trying to install the demo or bootstrap repos, I get the following:
```
computer:~ username$ go get github.com/asticode/go-astilectron-demo/...
# github.com/asticode/go-astilectron-bootstrap
go/src/github.com/asticode/go-astilectron-bootstrap/run.go:26: a.BaseDirectoryPath undefined (type *astilectron.Astilectron has no field or method BaseDirectoryPath)
go/src/github.com/asticode/go-astilectron-bootstrap/run.go:29: a.BaseDirectoryPath undefined (type *astilectron.Astilectron has no field or method BaseDirectoryPath)
go/src/github.com/asticode/go-astilectron-bootstrap/run.go:53: a.BaseDirectoryPath undefined (type *astilectron.Astilectron has no field or method BaseDirectoryPath)
```

This happens on both Mac and Windows with Go 1.8.3. Thanks for the help!

**Comment by asticode** [comment]
Yeah you're right about embedding the vendor and the resource files. But that's better if astilectron provides a way to do that so that most people use a validated way of doing it.

Regarding the error, it's "normal", some of my changes are in a branch I've not yet merged :(

I'll do it this week-end.

**Comment by spieglt** [comment]
Awesome! Last question for now: You say 

> the go generate command will use go-bindata to embed the vendor folder in your binary. That way when you’ll execute the binary, it will first disembed the vendor folder and recreate it on disk.

If I write an astilectron app now, how do I do this? I can generate the vendor.go file just fine, and then `go install` so that I get a binary, but then when I run it it still puts files under `go/src/github.com/asticode/go-astilectron-bootstrap/examples/vendor`. How do I get it to just write the files wherever the  main executable happens to be? I figure it's probably as simple as modifying a path in the `5.single_binary_distribution\main.go` file but I'm not sure what your NewDisembedderProvisioner function is doing exactly.

**Comment by asticode** [comment]
If I may add, I've created the bundler/bootstrap/demo yesterday so this is still pretty fresh. But this is definitely the way to go for astilectron.

Therefore if you're patient enough to wait until this week-end when I'll have time to implement the linux/windows portion of the bundler and merge other changes, I'd recommend you wait instead of implementing yourself embedding the vendor + resources files in your binary.

Since this is what the bundler will do, that would be duplicate work. And that would be a really great help for me to have another developer that can test the whole process!

Of course if you can't wait, I have no say whatsoever :D

Cheers

**Comment by spieglt** [comment]
Cool, no worries. Excited to give it a try this weekend. Thanks again.

**Comment by asticode** [comment]
As of now, you need to disembed the vendor.go and add this line:

```go
a.SetProvisioner(astilectron.NewDisembedderProvisioner(Asset, "../vendor/astilectron-v"+astilectron.VersionAstilectron+".zip", "../vendor/electron-v"+astilectron.VersionElectron+".zip"))
```

(update with the correct path of course)

**Comment by asticode** [comment]
@spieglt the whole process is working now for linux, mac and windows event though some nice-to-have features have not been implemented yet :)

You can check out the [demo](https://github.com/asticode/go-astilectron-demo) to see a working example.

For now the [bundler](https://github.com/asticode/go-astilectron-bundler) makes the assumption that you're using the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) (which is recommended).

I'll be adding the following things shortly:
- windows icon
- HTTP-like method to communicate between JS and GO but using the remote messaging (spawning your own web server is really not recommended)

I'd be happy to get your feedbacks upon testing it :)

Cheers

**Comment by asticode** [comment]
Windows icon has been added :)

**Comment by spieglt** [comment]
Awesome! Still getting some errors when trying to install the demo on Mac, however:
```
computer:~ user$ go get -u github.com/asticode/go-astilectron-demo/...
# github.com/asticode/go-astilectron-demo
go/src/github.com/asticode/go-astilectron-demo/main.go:27: undefined: Asset
go/src/github.com/asticode/go-astilectron-demo/main.go:84: undefined: RestoreAssets
```

**Comment by asticode** [comment]
@spieglt makes sense, I've forgot to add a basic `bind.go`. Should be fixed now.

Could you retry?

**Comment by spieglt** [comment]
The build process works like a dream! The resulting app does not open, however:
```
computer:darwin-amd64 user$ open Astilectron\ demo.app/
LSOpenURLsWithRole() failed with error -10810 for the file /Users/theronspiegl/go/src/github.com/asticode/go-astilectron-demo/output/darwin-amd64/Astilectron demo.app.
```
From a quick Googling it seems like something isn't executable that should be, but I checked that `Astilectron demo.app/Contents/MacOS/Astilectron demo` _is_ executable.
Also, just to let you know, I wrote an Electron app the other day and tried embedding it with go-bindata. I was going to write/launch it and use websockets for IPC, but the resulting binary was over 200MB and I see that the output of go-astilectron-bundler is too. My app really only needs to be ~10MB because there aren't any resources really so I tried my hand last night at building a Cocoa/Obj-C app with XCode and it actually wasn't too bad. Going to go with that for Flying Carpet I think and build something similar for Windows later. Working now on getting named pipes working for IPC. But I'm definitely glad to keep testing. Thanks again for all your help/work!

**Comment by asticode** [comment]
@spieglt I've run a few tests on MacOS and I've also encountered some errors with the icon paths not being absolute. I've pushed a fix in the bootstrap. Could you run a `go get -u github.com/asticode/go-astilectron-demo/...` and try again bundling + executing the demo?

I agree with you regarding the final size of the project. With astilectron, the size of the app before disembedding everything is ~50MB. After disembedding it is indeed ~200MB. Way too large. But the fact that you can run a cross-platform app that quickly almost without feeling any pain is too much of an advantage with Electron. But I understand why you're going an other route.

Good luck with building your app with Cocoa! And if you ever feel the need in the future, `go-astilectron` will still be there if you need a cross-platform GUI :D

Cheers

**Comment by spieglt** [comment]
Thanks! I ran the demo commands again and got this:
`FATA[0000] opening file  failed: open : no such file or directory`

**Comment by asticode** [comment]
closing this issue for now as the demo has it's own repo and I've updated the readme

**Comment by TableMountain** [comment]
The example at https://github.com/asticode/go-astilectron/tree/master/examples/5.single_binary_distribution/main.go
no longer exists, and is a broken link in the README.md instructions.

**Comment by asticode** [comment]
@TableMountain you're right, I've corrected the README so that it points to the [demo](https://github.com/asticode/go-astilectron-demo) that shows a nice example on how to use the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) and the [bundler](https://github.com/asticode/go-astilectron-bundler).
