### ISSUE TITLE
event.preventDefault() for go events

### ISSUE THREAD

**Issue by tehsphinx** [asticode/go-astilectron#48]
I am currently trying to implement a dialog to ask if the application should really be closed. (My App is a little management interface for a local server which should not be closed accidentally, since it shuts down the sever then.)

In Electron one would use `event.preventDefault()` to stop the app from closing. Is there another way to achieve this behaviour or could this be implemented? Basically this is about "feedback to JS" on executing events.

**Comment by asticode** [comment]
@tehsphinx I think that's a good feature to add natively. Here's what I've in mind:

- add a `ConfirmClose` attribute to `Astilectron` options that would represents a confirm dialog
- when quitting the app, the confirm dialog is showed and the app is closed only if the button on the left has been clicked

Does that sound good ?

**Comment by tehsphinx** [comment]
It would solve the example case of closing the app. But what about the general need to prevent the default from happening with any event? I have too little experience with electron yet, to suggest a proper solution but I hope I will get there soon.

Just ran into another 'issue' which I will create a new ticket for. Hopefully I can start creating PRs at some point soon rather than tickets.

**Comment by asticode** [comment]
@tehsphinx in the end I've added a `MessageBoxOnClose` window option that you can set up this way:

```go
MessageBoxOnClose: &astilectron.MessageBoxOptions{
	Buttons: []string{"Yes", "No"},
	ConfirmID: astilectron.PtrInt(0),
	Message: "Are you sure you want to quit?",
	Title:   "Confirm",
	Type:    astilectron.MessageBoxTypeQuestion,
}
```

If you're using the bundler to bundle your app, you'll need to `go get -u` it and run `make` once in its folder.

I see what you're saying about the general need to prevent default actions for any event but I'm afraid the issue has to be more precise than that to be fixed in a clean manner. Or at least I need more use cases regarding that particular issue.

Therefore I'll leave this issue open, in case somebody else has a use case regarding preventing default behavior of an electron's event

Cheers

**Comment by tehsphinx** [comment]
Thanks! I will think about it some more, too!
