### ISSUE TITLE
Find a better communication interface between GO and JS

### ISSUE THREAD

**Issue by asticode** [asticode/go-astilectron#55]
Moving [this issue](https://github.com/asticode/go-astilectron-demo/issues/4) into this repo.

**Comment by asticode** [comment]
I've refactored the remote messaging system so that we can use callbacks. Check out the doc:

- [send messages from GO to Javascript](https://github.com/asticode/go-astilectron#send-messages-from-go-to-javascript)
- [send messages from Javascript to GO](https://github.com/asticode/go-astilectron#send-messages-from-javascript-to-go)

I'll leave this issue opened for a while to get feedbacks, and I'll close it after some time.

Cheers

**Comment by connorlurring** [comment]
Does this still require you to make a MessageHandler, or should you just be able to register a listener in this fashion?

**Comment by asticode** [comment]
@connorlurring it depends whether you're using the bootstrap or not. If you're using the bootstrap you need to declare a `MessageHandler`. If you're not you need to use the JS and GO methods I've linked to in my previous post.

Does that make sense?

**Comment by gedw99** [comment]
@asticode Ben thinking about this whole problem again ... 

I found this !
https://github.com/iheanyi/go-electron-grpc

Have a look and see if you think its worth refactoring to use Astilectron...

I generally use GRPC-web (https://github.com/improbable-eng/grpc-web) because the client code can be JS OR golang that is then run through gopherjs ( and later WASM). So its cleaner.
