### ISSUE TITLE
Question about several window

### ISSUE THREAD

**Issue by JennyZmx** [asticode/go-astilectron#61]
This is the very first time for me to make a GUI so these questions may be really basic: 
1. Is my understanding correct: astilectron is a app (which refers to the GUI I made) and it may contain several windows? 
2. What is the difference between a window and a display? 
3. Does this binding allow multiple windows on at the same time? 
4. If it allows and I have multiple windows on, is it okey if I send a message from one window to go while go sends message to a different window (the main window)? 
Thank you so much for your help!

**Comment by JennyZmx** [comment]
One more question: does this binding allow writing or reading local files? I'm making a simple game app and want to record the highest scores of the player.

**Comment by asticode** [comment]
1. `astilectron` is not really an app. `astilectron` is a library that will allow your Golang app to download electron and communicate with it. If you use the [bootstrap](https://github.com/asticode/go-astilectron-bootstrap) and the [bundler](https://github.com/asticode/go-astilectron-bundler) you'll be able to bundle your Golang app so that it looks like a normal Mac app / Windows exe / Linux binary.

2. A display can be a screen, a TV, etc. (so a physicial stuff) whereas a window is an OS window (with the red little cross to close it :D)

3. Yes, you can create multiple windows with `astilectron`.

4. Yes you can communicate with 2 windows at the same time, whatever the direction of the communication.

5. Golang or NodeJS will allow to write/read local files, not `astilectron` per se.

Does that answer your questions?

**Comment by JennyZmx** [comment]
Yes. Thanks!
