### ISSUE TITLE
Listen() function in JavaScript

### ISSUE THREAD

**Issue by JennyZmx** [asticode/go-astilectron#62]
`astilectron.listen(function(message) {`
`    // This will send a message back to GO`
`     astilectron.send("I'm good bro")`
 `})`
I don't quite understand this part. Does that mean astilectron.listen() will return a "message"? 

BTW, is there any reference (like a GoDoc) so that I can check the detailed information of functions in JavaScript?

**Comment by JennyZmx** [comment]
BTW, do you mind if I just ask questions in issue tracker since there doesn't seem to have a forum for it?

**Comment by asticode** [comment]
The issue tracker is perfect to ask your questions, I may consider creating a website for `astilectron` if it reaches 1000 stars, but I don't think I'll add a forum as it's kind of a hassle to set up.

Regarding your first question, there are 2 directions in which you can send a message:

- from GO to JS => use the window's `Send()` GO method that will be caught by the `astilectron.listen()` JS method
- from JS to GO => use the `astilectron.send()` JS method that will be caught by a GO listener if you set it up with the event name `EventNameWindowEventMessage` (`window.On(EventNameWindowEventMessage, func(e Event) (deleteListener bool) {})`)

Unfortunately there's no doc for the JS code for now (I'm not a JS expert) but I welcome any contribution to solidify the JS part of `astilectron`. For now your best bet is to go through the code that is pretty straightforward: https://github.com/asticode/astilectron/blob/master/main.js

Does that answer your questions?

**Comment by JennyZmx** [comment]
Yes thanks!

**Comment by XWCHAO** [comment]
Hi,

I'm working on a chessboard game project using go it is currently a command-line version game. I plan to build a desktop application for this. Great to find your project here!

I'm going through the demo code, and I don't quite understand the "listen" part either. Is there any real user interaction in the demo, since it just prints out all file names under the root folder? I know I can send a message from GO to JS and from JS to GO. But is there a real example showing how to add this listener part for user interaction? (Take my project for example, user presses a button as going one step on the chess board, and JS sends this message to GO, lets Go calculate whether somebody wins this time, and GO sends back this win-or-not information back to JS)

**Comment by asticode** [comment]
@XWCHAO there's a small user interaction in the demo (in the menu you can select the type of style you want, and it send an event to the JS so that it updates the style), but let me take you through a whole JS <--> GO communication (in the code below I don't process errors for readibility purposes, however you should :D)

**Sending a message from GO to JS**

GO code:

```go
window.Send(bootstrap.MessageOut{Name: "my.event", Payload: "this is a string, but it can be any other type"})
```

JS code:

```js
 astilectron.listen(function(message) {
        switch (message.name) {
        case "my.event":
              console.log(message.payload)
              // or do whatever you want with the payload
              break;
        }
});
```

As you can see, the JS `listen` function must be called once on init, and should switch on the event name to react properly to the event it just received.

**Sending a message from JS to GO**

JS code:

```js
astilectron.send({"name": "my.event", payload: "this is your payload that can be an object as well"})
```

GO code:

this part is handled by the `MessageHandler` option of the bootstrap. So for instance:

```go
func handleMessages(w *astilectron.Window, m bootstrap.MessageIn) (payload interface{}, err error) {
	switch m.Name {
        case "my.event":
                 // You'll probably want to unmarshal the body of the payload to whatever type it is. I'll take a string for instance
                 var v string
                 json.Unmarshal(m.Payload, &v)
        }
}
```

**Conclusion**

Maybe you should check out a small project of mine, that implements a small user interaction as well: https://github.com/asticode/go-astivid.

Does that make things clearer?

Feel free to ask some more questions, your project seems really nice :)

**Comment by asticode** [comment]
@XWCHAO @JennyZmx I've refactored the remote messaging process so that it's easier to use. You can check out the doc:

- [send messages from GO to Javascript](https://github.com/asticode/go-astilectron#send-messages-from-go-to-javascript)
- [send messages from Javascript to Go](https://github.com/asticode/go-astilectron#send-messages-from-javascript-to-go)

Let me know if you have any questions or if that answers all your questions.

Cheers

**Comment by asticode** [comment]
@XWCHAO @JennyZmx I've also refactored the demo app which include examples on how to communicate between GO and Javascript with the bootstrap. Check it out!

**Comment by JennyZmx** [comment]
That's really helpful and more clear. Thank you so much for the work!
