### ISSUE TITLE
Add Dock object

### ISSUE THREAD

**Issue by txthinking** [asticode/go-astilectron#76]
Thanks for your great project.

I want to hide in taskbar now, also means:
After execute window.Hide() when close window, let it don't show when switch apps with CMD+TAB.
When click tray menu to reopen windows by window.Show(). 

Related: https://github.com/electron/electron/issues/422

**Comment by asticode** [comment]
@txthinking I won't have a lot of time to tackle that issue in the coming months but I'd be happy to review a PR. If you're interested, I can point you in the right directions :)

**Comment by asticode** [comment]
Referencing this for future use: https://github.com/electron/electron/blob/v1.8.1/docs/api/app.md#appdockbouncetype-macos

**Comment by asticode** [comment]
@txthinking I've just added support to the Dock object. Remember to fetch updates to the dependencies and the bundler, as well as make the bundler so that it references the correct astilectron version.

 You can find the doc [here](https://github.com/asticode/go-astilectron#dock-macosx-only).

I'll close this issue for now, let me know if you're experiencing any problems.

Cheers

**Comment by txthinking** [comment]
Sorry for checking late, thank you very much.

**Comment by asticode** [comment]
no worries, let me know if you're experiencing any problems
