### ISSUE TITLE
Selenium webdriver automation issue

### ISSUE THREAD

**Issue by igor-rubis** [asticode/go-astilectron#81]
Hello,

Could you please take a look at my issue? I'm trying to automate go-astilectron app testing and I'm facing an issue on the app start. The chrome driver service can't start it properly.

I tryed two ways:

1. With spectron framework (https://github.com/electron/spectron)
I used the example from the README and it seems like it can't handle a promise returning from app.start()
In this case the app starts but the test code can't interact with it.

2. I used java webdriver lib, set the app as the chrome executable and got the following exception
```
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
```

The point is that either approaches work perfectly with the demo application from electron repo (https://github.com/electron/electron-api-demos/releases).
Can you please give any information on the chromium your application starts in? May be you use any custom chromium distribution?

Thank you in advance.

**Comment by asticode** [comment]
@igor-rubis you don't mention any GO in your comment, is that because you don't use any? if so I'm not sure this is the perfect project for you since this project is full GO

**Comment by igor-rubis** [comment]
Thanks for quick reply.
Well, yes, I don't directly work with the Go code. I need to automate functional testing of the go-astilectron application. Since the oiriginal electron app runs in chromium, its functional testing can be automated with Selenium webdriver and I managed to do it with the original electron app. I've just started the research of how to do it, since my team decided to use go-astilectron to build our own application.
So I'm just wondering if you could give any information on which kind of chromium you use for go-astilectron.

**Comment by asticode** [comment]
@igor-rubis I may not be understanding fully what you're saying, therefore if I misunderstood you, please correct me. 

What I understand is that you want to automate functional testing of the go-astilectron application without actually running the GO code. **As far as I'm concerned, this may not work**, since the Electron app is only a proxy app that relies on the GO code to provide valuable information or commands (such window creation, menu creation, etc.).

If you run manually the Electron app, it should fail as it can't connect to the TCP server GO is normally providing (which should be explaining the second error you're experiencing).

I think you can only run the full GO app to automate your functional testing otherwise it will fail.

PS: regarding the chromium version the project is using, this is the same as the one used by the electron version it's using, which means it's the chromium version of the 1.8.1 version of electron.

**Comment by igor-rubis** [comment]
Not exactly. I was saying that I'm not the one writes the go-astilectron application. But I'm going to test already built app. For the investigation purpose I compiled your demo app (https://github.com/asticode/go-astilectron-demo) and tryed to start and test it from my code using Selenium Webdriver written in Java and JS. But for some reason the Chrome driver service can't start a binary compiled from the demo app and I get an exception. When I start the binary manually it works perfectly so the app's GO code is definitely executed.
I'm trying to deal with this issue so I'd be grateful for any helpful information on how the go-astilectron app run and which chromium does it use.

**Comment by asticode** [comment]
@igor-rubis the way it works is pretty straight-forward: when the GO code is executed, it spawns a TCP server then it executes the astilectron electron app which connects to the server. Then whenever the GO code requests something from Electron, it sends the request through the TCP server, and whenever Electron sends something to the GO code it sends it throught the TCP server.

Again, this project doesn't handle directly the chromium version since it only executes an Electron app using the Electron binary. The chromium version is the one used by Electron in their 1.8.1 version.

Does that answer your question?

**Comment by Noofbiz** [comment]
I would actually try RemoteWebDriver or something higher up, like EventFiringWebDriver than ChromeDriver, because Chromium isn't exactly Chrome and could cause issues.

**Comment by igor-rubis** [comment]
Thanks for answers, I found the original issue's cause. Selenium could not start the app because it passes some flags to the command like the following:
```bash
/path/to/demo/app --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.Z87IH1/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12590 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.du9UVA data:
```
The application didn't start since its Go part doesn't know such flags. It returns a message:
```bash
flag provided but not defined: -disable-background-networking
Usage of /path/to/demo/app:
  -d	enables the debug mode (default true)
  -logger-app-name string
    	the logger's app name
  -v	if true, then log level is debug
```
We've dealt with this issue already.

But currently I'm encountering the new one - WebDriverException: chrome not reachable
For some reason selenium can't interact with the app after its start.

**Comment by asticode** [comment]
@igor-rubis did you manage to fix your last issue?

**Comment by igor-rubis** [comment]
@asticode Not yet. Seems like the point is that the app binary triggers the go part of the app and then the go part starts astilectron part with the browser and because of this Selenium can't interact with browser. I raised an issue in the chrome driver bug tracker https://bugs.chromium.org/p/chromedriver/issues/detail?id=2341

**Comment by igor-rubis** [comment]
@Noofbiz unfortunately such approach doesn't work either
> you can open a web browser to localhost:$PORT where $PORT is the port that the TCP server is running and test like you would a typical website.

**Comment by asticode** [comment]
@igor-rubis [this issue](https://github.com/asticode/go-astilectron/issues/90) may be of interest to you :)

**Comment by asticode** [comment]
Really nice, I didn't know that :)

Cheers for tackling this issue :)
