### ISSUE TITLE
How to add custom window to tray

### ISSUE THREAD

**Issue by asticode** [asticode/go-astilectron#97]

**Comment by john-dev** [comment]
I love StautsBar apps on macOS since they don't mess around with my dockbar nor the programm switch (cmd+tab)

Version 0.20.0 supports bounds (rectangle) for tray click events.
` 	tray.On(astilectron.EventNameTrayEventClicked, func(e astilectron.Event) (deleteListener bool) {
		if isShow {
			w.Hide()
		} else {
			width := 500 //total window width
			w.Move(*e.Bounds.PositionOptions.X-*width/2+(*e.Bounds.SizeOptions.Width/2), 0)
		}

		return
	})`

This results into an application thats fits perfectly fine centered below the statusbar icon:
[http://bro7.com/uploads/TW9vdklUIEdtYkg/8l1Slt1sfGdwBQmBGf9zKE0SWVmRXhBvRvH5XxoSYg/pb-eBOu3J4iOv.png](url)

**Comment by asticode** [comment]
Cheers
